spring.application.name=cloud-task-api
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudtask
spring.datasource.username=postgres
spring.datasource.password=Mi7@q5tg8+

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
