CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP,
                deleted BOOLEAN NOT NULL,
                deleted_at TIMESTAMP,
                updated_at TIMESTAMP,
                password VARCHAR(255),
                username VARCHAR(255),
                role VARCHAR(255),

                CONSTRAINT users_role_check
                     CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP,
                deleted BOOLEAN NOT NULL,
                deleted_at TIMESTAMP,
                updated_at TIMESTAMP,
                description VARCHAR(255),
                priority VARCHAR(255),
                status VARCHAR(255),
                title VARCHAR(255) NOT NULL,
                due_date DATE,
                owner_id BIGINT NOT NULL,

                CONSTRAINT tasks_priority_check
                    CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),

                CONSTRAINT tasks_status_check
                    CHECK (status IN (
                                             'TODO',
                                             'IN_PROGRESS',
                                             'COMPLETED',
                                             'CANCELLED'
                               )),

                CONSTRAINT fk_task_owner
                    FOREIGN KEY (owner_id)
                    REFERENCES users(id)
);