CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL ,
    resource_type VARCHAR(50),
    resource_id BIGINT,
    changes JSONB,
    ip_address VARCHAR(45),

    user_agent TEXT,

    created_at TIMESTAMP NOT NULL ,

    CONSTRAINT chk_audit_action
        CHECK (
            action IN(
                    'USER_LOGIN',
                    'USER_LOGOUT',
                    'TOKEN_REFRESH',
                    'TASK_CREATED',
                    'TASK_UPDATED',
                    'TASK_DELETED'
                     )
             ),
    CONSTRAINT chk_audit_resource_type
        CHECK (
            resource_type IS NULL
            OR resource_type IN (
                    'TASK',
                    'SESSION'
            )
        )
);